#!/usr/bin/env bash
set -e

echo "🔧 Setting up Strapi Development Instance..."

# Generate secrets
echo "Generating Strapi secrets..."
APP_KEY=$(openssl rand -base64 32)
API_TOKEN_SALT=$(openssl rand -base64 32)
ADMIN_JWT_SECRET=$(openssl rand -base64 32)
TRANSFER_TOKEN_SALT=$(openssl rand -base64 32)
JWT_SECRET=$(openssl rand -base64 32)

# Project slug: required for Docker names (no compose default). Prefer env or existing .env.
if [ -n "${PROJECT_SLUG:-}" ]; then
  :
elif [ -f .env ]; then
  PROJECT_SLUG=$(grep "^PROJECT_SLUG=" .env | cut -d'=' -f2 | tr -d '"' | tr -d "'") || true
fi
if [ -z "${PROJECT_SLUG:-}" ]; then
  echo "Error: PROJECT_SLUG is not set. Export it (e.g. export PROJECT_SLUG=myapp) or create .env with PROJECT_SLUG=... matching your GPP project name."
  exit 1
fi

# Create .env file
cat > .env << EOF
#===============================================================================
# STRAPI DEVELOPMENT - ENVIRONMENT VARIABLES
#===============================================================================
# Generated by setup.sh on $(date)
#===============================================================================

PROJECT_SLUG=${PROJECT_SLUG}

SITE_NAME=Strapi Development
STRAPI_URL=http://localhost:1338
FRONTEND_URL=http://localhost:3001

ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=admin

MYSQL_DATABASE=strapi_dev
MYSQL_USER=strapi
MYSQL_PASSWORD=strapi
MYSQL_ROOT_PASSWORD=root

STRAPI_PORT=1338
PHPMYADMIN_PORT=9092
MYSQL_PORT=3308

TIMEZONE=America/New_York

# Strapi Secrets (auto-generated)
STRAPI_APP_KEY=${APP_KEY}
STRAPI_API_TOKEN_SALT=${API_TOKEN_SALT}
STRAPI_ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
STRAPI_TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
STRAPI_JWT_SECRET=${JWT_SECRET}
EOF

echo "✅ .env file created"
echo ""
echo "Next steps:"
echo "1. Review and update .env if needed"
echo "2. Run: docker compose --env-file .env up -d (or ./dev.sh) to start Strapi"
echo "3. Access admin at: http://localhost:1338/admin"
echo "   (GraphQL plugin is installed automatically on first start.)"

